service: lighthouse-auditor

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

plugins:
  - serverless-offline
  - serverless-plugin-chrome
  - serverless-attach-managed-policy
  - serverless-webpack  

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'yarn'   # Packager that will be used to package your external modules
  chrome:
      flags:
        - --window-size=1680x1050
        - --hide-scrollbars
        - --ignore-certificate-errors
        - --headless
        - --disable-gpu
        - --no-sandbox
        - --homedir=/tmp/randompath0
        - --single-process
        - --data-path=/tmp/randompath1
        - --disk-cache-dir=/tmp/randompath2
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  # tableName: ${self:custom.stage}-audits
  # Set our DynamoDB throughput for prod and all other non-prod stages.
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  # Load our webpack config
  # webpack:
  #   webpackConfig: ./webpack.config.js
  #   includeModules: true

package:
  individually: true

        
resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}

functions:
  auditor:
    handler: audit/index.handler
    timeout: 180
    events:
      - schedule:
          name: lighthouse-audit-trigger
          description: 'Audit the input target.'
          rate: rate(5 minutes)
          enabled: true
          input:
            target: https://www.bbc.com/
            mobile: false
