service: lighthouse-auditor

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
        - dynamodb:*
      Resource: "*"

plugins:
  - serverless-plugin-chrome
  - serverless-attach-managed-policy

custom:
  chrome:
      flags:
        - --window-size=1680x1050
        - --single-process
        - --data-path=/tmp/randompath1
        - --disk-cache-dir=/tmp/randompath2
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:custom.stage}-auditsTable
  # Set the table name here so we can use it while testing locally
  # tableName: ${self:custom.stage}-audits
  # Set our DynamoDB throughput for prod and all other non-prod stages.
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  # Load our webpack config
  # webpack:
  #   webpackConfig: ./webpack.config.js
  #   includeModules: true

resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}

functions:
  audit:
    handler: audit/index.handler
    timeout: 60
    events:
      - schedule:
          rate: rate(1 day)