service: lighthouse-auditor

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

plugins:
  - serverless-plugin-chrome
  - serverless-attach-managed-policy

custom:
  chrome:
      flags:
        - --window-size=1680x1050
        - --hide-scrollbars
        - --ignore-certificate-errors
        - --headless
        - --disable-gpu
        - --no-sandbox
        - --homedir=/tmp/randompath0
        - --single-process
        - --data-path=/tmp/randompath1
        - --disk-cache-dir=/tmp/randompath2

functions:
  auditor:
    handler: handler.audit
    timeout: 180
    events:
      - schedule:
          name: lighthouse-audit-trigger
          description: 'Audit the input target.'
          rate: rate(5 minutes)
          enabled: true
          input:
            target: https://www.bbc.com/
            mobile: false
